# Generated by Django 4.0.3 on 2022-06-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_todo_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('WORKING', 'WORKING'), ('DONE', 'DONE'), ('OVERDUE', 'OVERDUE')], default='OPEN', max_length=10),
        ),
    ]
